### ISSUE TITLE
Fazer com que IU.py inicialize tabuleiro uma única vez

### ISSUE THREAD

**Issue by petrolifero** [Grupo-de-ESII/Jogo-de-Xadrez#26]

**Comment by rbleardini** [comment]
Pelo menos motivo que tabuleiro recebia jogador como argumento. Depois eu removo.

**Comment by petrolifero** [comment]
É que estou cuidando de uma branch para xeque em que as peças tem mais de um jogador, então não sabia se isso tinha alguma coisa a ver. Provavelmente não. :)
