### ISSUE TITLE
Organizar código em pastas src/assets/etc

### ISSUE THREAD

**Issue by juliafalcao** [Grupo-de-ESII/Jogo-de-Xadrez#6]
O código está atualmente organizado em pastas como IA, Interface, etc., as quais só tem um arquivo dentro, o que é desnecessário. Pretendo refatorar para termos todas as classes em uma pasta src.

**Comment by petrolifero** [comment]
Fazemos isso em qual branch? Tipo, se fizermos na master, seguiremos com o esquema atual na integração. O git vai pegar de boas quando der merge?
