### ISSUE TITLE
Mudar cores dos jogadores 1 e 2

### ISSUE THREAD

**Issue by juliafalcao** [Grupo-de-ESII/Jogo-de-Xadrez#7]

**Comment by petrolifero** [comment]
```
class Tabuleiro:
    def __init__(self):
        self.pecas = [[None for j in range(8)] for i in range(8)]
        self.pilha = []

        self.jogador_1 = Jogador('branca')
        self.jogador_2 = Jogador('preta')
...
```

Esta resolvido na branch integração-regras-ia

Wallace consertou antes que eu pudesse ver

Peço que nas próximas issues que fizermos, coloquemos um codigo de exemplo(de teste) com saida esperada e atual, para facilitar a comunicação :) 

10/10 julia

**Comment by wallacebaleroni** [comment]
Comigo é assim, antes de tu ver que tem bug eu já corrigi
